### ISSUE TITLE
LimitMobPerChunkCommand

### ISSUE THREAD

**Issue by Lucasmellof** [TheMartinfer22/LimitThisMob#1]
Heey, tudo bom?
Uma pequena sugestão, você não precisa ficar instanciando uma nova HashMap toda vez que executa uma comando... É melhor usar fazer um Cache de todas as informações e salvar quando o plugin for finalizado dentro do `onDisable`

![image](https://user-images.githubusercontent.com/23638982/129908211-abaf1917-0bf9-42b0-b17d-6d2c1a2b9d9b.png)

(A proposito, seu código melhorou muito desde a última vez que eu vi... Outra coisa, não lembro se você tem algum código meu, mas se tiver da uma olhada neles, pode ser que tenha alguma coisa útil para você lá. Ainda vou deixar uns repos públicos no meu Github, aí você da umas olhadas. Eu tenho um repo que seria perfeito para você ter umas ideias, mas infelizmente não posso deixar ele público, mas se quiser eu posso te mostrar algumas partes dele. ^-^)

**Comment by TheMartinfer22** [comment]
Já alterei tudo, coloquei em H2 tudo por limitações futuras por motivos do cast do HashMap e adicionei leitura somente para cache ao iniciar o servidor, nunca utilizei muito perda de dados para o onDisable, não me leva muita confiança.
Só estou alterando algumas regras de negócio para já atualizar o mesmo, mas obrigado pelo feedback!

**Comment by Lucasmellof** [comment]
> Já alterei tudo, coloquei em H2 tudo por limitações futuras por motivos do cast do HashMap e adicionei leitura somente para cache ao iniciar o servidor, nunca utilizei muito perda de dados para o onDisable, não me leva muita confiança.
> Só estou alterando algumas regras de negócio para já atualizar o mesmo, mas obrigado pelo feedback!

Depende muito de como você vai utilizar o onDisable, mas ele vai acontecer exatamente na hora que o plugin vai finalizar, o Bukkit vai executar o método, se você não finalizar nenhuma conexão antes de salvar você não vai perder nada.

**Comment by TheMartinfer22** [comment]
Vou fazer uns testes no onDisable uma hora dessas, nunca dei muita importância.
